% Generated by MATLAB(R) 9.14 (R2023a) and Communications Toolbox 8.0 (R2023a).
% Generated on: 13-Apr-2024 13:05:40

%% Generating QAM waveform
% QAM configuration
M = 4; 	 % Modulation order
% input bit source:
in = randi([0, 1], 60000, 1);

% Generation
waveform0 = qammod(in, M, 'gray', 'InputType', 'bit', 'UnitAveragePower', true);

Fs = 1000; 								 % Specify the sample rate of the waveform in Hz

%% Impairments
% AWGN
waveform = awgn(waveform0, 20, 'measured');

%% Visualize
% Time Scope
timeScope = timescope('SampleRate', Fs, ...
    'TimeSpanOverrunAction', 'scroll', ...
    'TimeSpanSource', 'property', ...
    'TimeSpan', 0.03);
timeScope(waveform);
release(timeScope);

dur = 29.9990;
t = 0:1/Fs:dur;

% Constellation Diagram
constel = comm.ConstellationDiagram('ColorFading', true, ...
    'ShowTrajectory', 0, ...
    'ShowReferenceConstellation', false);
constel(waveform);
release(constel);

load('HPF_mc.mat');
% Apply filter
filtered_signal = filter(HPF_c, waveform);

% Create 1st spectrumAnalyzer display - Original wavform
sa0 = spectrumAnalyzer;
spectrum0 = spectrumAnalyzer('SampleRate', Fs);
spectrum0(waveform0);
release(spectrum0);

% Create 2nd spectrumAnalyzer display - Noisy wavform
sa1 = spectrumAnalyzer;
spectrum1 = spectrumAnalyzer('SampleRate', Fs);
spectrum1(waveform);
release(spectrum1);

% Create 3rd spectrumAnalyzer display - filtered wavform
sa2 = spectrumAnalyzer;
spectrum2 = spectrumAnalyzer('SampleRate', Fs);
spectrum2(filtered_signal);
release(spectrum2);

figure(1);
subplot(2,1,1);
plot(t(1:301), waveform(1:301), 'b', t(1:301), waveform0(1:301), 'r');
title('Noisy vs Original');
xlabel('Time (s)');
ylabel('Amplitude');
legend('Noisy Signal', 'Original');
ylim([-1.5,1.5]);

figure(1);
subplot(2,1,2);
plot(t(1:301), waveform(1:301), 'b', t(1:301), filtered_signal(1:301), 'r');
title('Noisy vs Filtered Signal');
xlabel('Time (s)');
ylabel('Amplitude');
legend('Noisy Signal', 'Filtered Signal');
ylim([-1.5,1.5]);